# Generated by Django 5.0 on 2025-10-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
