# Generated by Django 5.0 on 2025-10-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='preferred_skills',
        ),
        migrations.RemoveField(
            model_name='job',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs.skill'),
        ),
    ]
