# Generated by Django 5.0 on 2025-10-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_preferred_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='preferred_skills',
            field=models.ManyToManyField(blank=True, related_name='preferred_for_jobs', to='jobs.skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='required_for_jobs', to='jobs.skill'),
        ),
    ]
