# Generated by Django 5.0 on 2025-10-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_preferred_skills_job_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
