# Generated by Django 5.0 on 2025-10-13 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobseekers', to='jobs.skill'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseekerprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiterprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
