# Generated by Django 5.0 on 2025-10-26 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobseekerprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiterprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='jobseekerprofile',
            index=models.Index(fields=['city', 'state_region'], name='accounts_jo_city_33a800_idx'),
        ),
        migrations.AddIndex(
            model_name='jobseekerprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='accounts_jo_latitud_7acf2b_idx'),
        ),
        migrations.AddIndex(
            model_name='recruiterprofile',
            index=models.Index(fields=['city', 'state_region'], name='accounts_re_city_296ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='recruiterprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='accounts_re_latitud_8a2e63_idx'),
        ),
    ]
