# Generated by Django 5.0 on 2025-10-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
