# Generated by Django 5.0 on 2025-10-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
